import type { Product, Category, Brand, Banner } from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Чоловічий компресійний одяг",
    slug: "men",
    description: "Компресійний одяг для чоловіків",
    image: "https://picsum.photos/seed/men-category/600/400",
    children: [
      { id: "1-1", name: "Комплект 2 в 1", slug: "men-2v1", parentId: "1" },
      { id: "1-2", name: "Комплект 3 в 1", slug: "men-3v1", parentId: "1" },
      { id: "1-3", name: "Комплект 4 в 1", slug: "men-4v1", parentId: "1" },
      { id: "1-4", name: "Комплект 5 в 1", slug: "men-5v1", parentId: "1" },
    ],
  },
  {
    id: "3",
    name: "Дитячий компресійний одяг",
    slug: "kids",
    description: "Компресійний одяг для дітей",
    image: "https://picsum.photos/seed/kids-category/600/400",
    children: [
      { id: "3-1", name: "Комплект 3 в 1", slug: "kids-3v1", parentId: "3" },
      { id: "3-2", name: "Комплект 4 в 1", slug: "kids-4v1", parentId: "3" },
    ],
  },
];

export const brands: Brand[] = [
  { id: "b1", name: "Compex Pro", slug: "compex-pro" },
  { id: "b2", name: "Athletic Edge", slug: "athletic-edge" },
  { id: "b3", name: "FitWear", slug: "fitwear" },
];

const productImages: Record<string, string[]> = {
  p1: [
    "https://picsum.photos/seed/compex-pro-1/600/800",
    "https://picsum.photos/seed/compex-pro-1b/600/800",
    "https://picsum.photos/seed/compex-pro-1c/600/800",
  ],
  p2: [
    "https://picsum.photos/seed/compex-elite-2/600/800",
    "https://picsum.photos/seed/compex-elite-2b/600/800",
    "https://picsum.photos/seed/compex-elite-2c/600/800",
  ],
  p3: [
    "https://picsum.photos/seed/compex-rash-3/600/800",
    "https://picsum.photos/seed/compex-rash-3b/600/800",
    "https://picsum.photos/seed/compex-rash-3c/600/800",
  ],
  p4: [
    "https://picsum.photos/seed/compex-flex-4/600/800",
    "https://picsum.photos/seed/compex-flex-4b/600/800",
    "https://picsum.photos/seed/compex-flex-4c/600/800",
  ],
  p5: [
    "https://picsum.photos/seed/compex-power-5/600/800",
    "https://picsum.photos/seed/compex-power-5b/600/800",
    "https://picsum.photos/seed/compex-power-5c/600/800",
  ],
  p6: [
    "https://picsum.photos/seed/compex-junior-6/600/800",
    "https://picsum.photos/seed/compex-junior-6b/600/800",
    "https://picsum.photos/seed/compex-junior-6c/600/800",
  ],
  p7: [
    "https://picsum.photos/seed/compex-thermo-7/600/800",
    "https://picsum.photos/seed/compex-thermo-7b/600/800",
    "https://picsum.photos/seed/compex-thermo-7c/600/800",
  ],
  p8: [
    "https://picsum.photos/seed/compex-apex-8/600/800",
    "https://picsum.photos/seed/compex-apex-8b/600/800",
    "https://picsum.photos/seed/compex-apex-8c/600/800",
  ],
};

export const products: Product[] = [
  {
    id: "p1",
    name: "Компресійна футболка Pro Max",
    slug: "compression-tshirt-pro-max",
    description:
      "Високоякісна компресійна футболка з мікрофібри. Забезпечує ідеальну підтримку м'язів під час інтенсивних тренувань. Дихаючий матеріал відводить вологу, забезпечуючи комфорт навіть при найвищих навантаженнях. Ідеальна для бігу, фітнесу, бойових мистецтв та будь-яких силових тренувань.",
    shortDesc: "Преміальна компресійна футболка для професійних спортсменів",
    price: 1299,
    oldPrice: 1599,
    gender: "MEN",
    isActive: true,
    isFeatured: true,
    isNew: false,
    isSale: true,
    inStock: true,
    stockQty: 45,
    categoryId: "1",
    category: categories[0],
    brandId: "b1",
    brand: brands[0],
    images: productImages.p1.map((url, i) => ({
      id: `img-p1-${i}`,
      url,
      alt: `Компресійна футболка Pro Max - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s1", name: "S", inStock: true },
      { id: "s2", name: "M", inStock: true },
      { id: "s3", name: "L", inStock: true },
      { id: "s4", name: "XL", inStock: true },
      { id: "s5", name: "XXL", inStock: false },
    ],
    colors: [
      { id: "c1", name: "Чорний", hex: "#1A1A1A" },
      { id: "c2", name: "Червоний", hex: "#E31837" },
      { id: "c3", name: "Сірий", hex: "#6B7280" },
    ],
    reviews: [
      {
        id: "r1",
        rating: 5,
        title: "Найкраща футболка!",
        comment:
          "Купив для тренувань у залі. Компресія відчувається, матеріал дуже приємний. Рекомендую!",
        isApproved: true,
        userId: "u1",
        user: { name: "Олександр", email: "test@test.com" },
        productId: "p1",
        createdAt: new Date("2026-05-15"),
      },
      {
        id: "r2",
        rating: 4,
        title: "Гарна якість",
        comment:
          "Якість на висоті, але хотілося б більше розмірів в наявності.",
        isApproved: true,
        userId: "u2",
        user: { name: "Марія", email: "test2@test.com" },
        productId: "p1",
        createdAt: new Date("2026-05-20"),
      },
    ],
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p2",
    name: "Компресійні шорти Elite",
    slug: "compression-shorts-elite",
    description:
      "Компресійні шорти з підтримкою м'язів стегон. Виготовлені з високотехнологічного матеріалу, що забезпечує максимальну компресію та自由ний рух. Ідеально підходять для бігу, кроссфіту та єдиноборств.",
    shortDesc: "Професійні компресійні шорти для інтенсивних тренувань",
    price: 999,
    gender: "MEN",
    isActive: true,
    isFeatured: true,
    isNew: true,
    isSale: false,
    inStock: true,
    stockQty: 32,
    categoryId: "1",
    category: categories[0],
    brandId: "b2",
    brand: brands[1],
    images: productImages.p2.map((url, i) => ({
      id: `img-p2-${i}`,
      url,
      alt: `Компресійні шорти Elite - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s6", name: "S", inStock: true },
      { id: "s7", name: "M", inStock: true },
      { id: "s8", name: "L", inStock: true },
      { id: "s9", name: "XL", inStock: true },
    ],
    colors: [
      { id: "c4", name: "Чорний", hex: "#1A1A1A" },
      { id: "c5", name: "Синій", hex: "#2563EB" },
    ],
    reviews: [],
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p3",
    name: "Рашгард Pro Compression",
    slug: "rashguard-pro-compression",
    description:
      "Рашгард преміум класу для MMA, бразилського джиу-джитсу та муай-тай. Захищає шкіру від подразнень та забезпечує компресію м'язів. Шви Flatlock для максимального комфорту.",
    shortDesc: "Професійний рашгард для єдиноборств",
    price: 1499,
    oldPrice: 1899,
    gender: "MEN",
    isActive: true,
    isFeatured: true,
    isNew: false,
    isSale: true,
    inStock: true,
    stockQty: 28,
    categoryId: "1",
    category: categories[0],
    brandId: "b1",
    brand: brands[0],
    images: productImages.p3.map((url, i) => ({
      id: `img-p3-${i}`,
      url,
      alt: `Рашгард Pro Compression - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s10", name: "S", inStock: true },
      { id: "s11", name: "M", inStock: true },
      { id: "s12", name: "L", inStock: true },
      { id: "s13", name: "XL", inStock: true },
      { id: "s14", name: "XXL", inStock: true },
    ],
    colors: [
      { id: "c6", name: "Чорний", hex: "#1A1A1A" },
      { id: "c7", name: "Червоний", hex: "#E31837" },
    ],
    reviews: [
      {
        id: "r3",
        rating: 5,
        title: "Топ якість!",
        comment:
          "Використовую для тренувань MMA. Рашгард тримається ідеально, компресія відмінна.",
        isApproved: true,
        userId: "u3",
        user: { name: "Дмитро", email: "test3@test.com" },
        productId: "p3",
        createdAt: new Date("2026-05-25"),
      },
    ],
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p4",
    name: "Жіночі компресійні легінси Flex",
    slug: "women-leggings-flex",
    description:
      "Елегантні компресійні легінси для жінок. Висота талії забезпечує комфорт під час тренувань. Матеріал з ефектом second-skin ідеально облягає тіло, підтримуючи м'язи.",
    shortDesc: "Преміальні жіночі легінси з високою талією",
    price: 1199,
    gender: "WOMEN",
    isActive: true,
    isFeatured: true,
    isNew: true,
    isSale: false,
    inStock: true,
    stockQty: 38,
    categoryId: "2",
    category: categories[1],
    brandId: "b3",
    brand: brands[2],
    images: productImages.p4.map((url, i) => ({
      id: `img-p4-${i}`,
      url,
      alt: `Жіночі компресійні легінси Flex - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s15", name: "XS", inStock: true },
      { id: "s16", name: "S", inStock: true },
      { id: "s17", name: "M", inStock: true },
      { id: "s18", name: "L", inStock: true },
      { id: "s19", name: "XL", inStock: true },
    ],
    colors: [
      { id: "c8", name: "Чорний", hex: "#1A1A1A" },
      { id: "c9", name: "Бордовий", hex: "#8B0000" },
      { id: "c10", name: "Сірий", hex: "#9CA3AF" },
    ],
    reviews: [],
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p5",
    name: "Жіночий компресійний топ Power",
    slug: "women-compression-top-power",
    description:
      "Компресійний спортивний топ з підтримкою. Ідеальний для йоги, пілатесу, бігу та фітнесу. Дихаючий матеріал та ергономічний крій забезпечують комфорт на весь день.",
    shortDesc: "Спортивний компресійний топ для жінок",
    price: 899,
    oldPrice: 1099,
    gender: "WOMEN",
    isActive: true,
    isFeatured: false,
    isNew: false,
    isSale: true,
    inStock: true,
    stockQty: 25,
    categoryId: "2",
    category: categories[1],
    brandId: "b3",
    brand: brands[2],
    images: productImages.p5.map((url, i) => ({
      id: `img-p5-${i}`,
      url,
      alt: `Жіночий компресійний топ Power - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s20", name: "XS", inStock: true },
      { id: "s21", name: "S", inStock: true },
      { id: "s22", name: "M", inStock: true },
      { id: "s23", name: "L", inStock: true },
    ],
    colors: [
      { id: "c11", name: "Чорний", hex: "#1A1A1A" },
      { id: "c12", name: "Білий", hex: "#FFFFFF" },
    ],
    reviews: [],
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p6",
    name: "Дитяча компресійна футболка Junior",
    slug: "kids-compression-tshirt-junior",
    description:
      "Компресійна футболка для дітей від 8 до 16 років. М'який, безпечний матеріал. Ідеально підходить для занять спортом, бойовими мистецтвами та активного відпочинку.",
    shortDesc: "Компресійна футболка для юних спортсменів",
    price: 699,
    gender: "KIDS",
    isActive: true,
    isFeatured: true,
    isNew: true,
    isSale: false,
    inStock: true,
    stockQty: 50,
    categoryId: "3",
    category: categories[2],
    brandId: "b2",
    brand: brands[1],
    images: productImages.p6.map((url, i) => ({
      id: `img-p6-${i}`,
      url,
      alt: `Дитяча компресійна футболка Junior - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s24", name: "128", inStock: true },
      { id: "s25", name: "140", inStock: true },
      { id: "s26", name: "152", inStock: true },
      { id: "s27", name: "164", inStock: true },
    ],
    colors: [
      { id: "c13", name: "Чорний", hex: "#1A1A1A" },
      { id: "c14", name: "Синій", hex: "#2563EB" },
    ],
    reviews: [],
    createdAt: new Date("2026-05-20"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p7",
    name: "Термокомпресійна футболка Thermo",
    slug: "thermal-compression-tshirt",
    description:
      "Термокомпресійна футболка для тренувань на вулиці в холодну погоду. Зберігає тепло тіла, забезпечуючи компресію м'язів. Ідеальна для бігу, велоспорту та зимових тренувань.",
    shortDesc: "Термокомпресійна футболка для холодної погоди",
    price: 1599,
    gender: "UNISEX",
    isActive: true,
    isFeatured: false,
    isNew: true,
    isSale: false,
    inStock: true,
    stockQty: 20,
    categoryId: "4",
    category: categories[3],
    brandId: "b1",
    brand: brands[0],
    images: productImages.p7.map((url, i) => ({
      id: `img-p7-${i}`,
      url,
      alt: `Термокомпресійна футболка Thermo - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s28", name: "S", inStock: true },
      { id: "s29", name: "M", inStock: true },
      { id: "s30", name: "L", inStock: true },
      { id: "s31", name: "XL", inStock: true },
    ],
    colors: [
      { id: "c15", name: "Чорний", hex: "#1A1A1A" },
      { id: "c16", name: "Темно-сірий", hex: "#374151" },
    ],
    reviews: [],
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "p8",
    name: "Чоловічий компресійний комплект Apex",
    slug: "men-compression-set-apex",
    description:
      "Повний компресійний комплект: футболка + шорти. Ідеальний для комплексних тренувань. Максимальна підтримка м'язів та自由ний рух.",
    shortDesc: "Комплект компресійного одягу для чоловіків",
    price: 1999,
    oldPrice: 2499,
    gender: "MEN",
    isActive: true,
    isFeatured: true,
    isNew: false,
    isSale: true,
    inStock: true,
    stockQty: 15,
    categoryId: "1",
    category: categories[0],
    brandId: "b1",
    brand: brands[0],
    images: productImages.p8.map((url, i) => ({
      id: `img-p8-${i}`,
      url,
      alt: `Чоловічий компресійний комплект Apex - фото ${i + 1}`,
      isPrimary: i === 0,
      order: i,
    })),
    sizes: [
      { id: "s32", name: "S", inStock: true },
      { id: "s33", name: "M", inStock: true },
      { id: "s34", name: "L", inStock: true },
      { id: "s35", name: "XL", inStock: true },
    ],
    colors: [
      { id: "c17", name: "Чорний", hex: "#1A1A1A" },
      { id: "c18", name: "Червоний/Чорний", hex: "#E31837" },
    ],
    reviews: [
      {
        id: "r4",
        rating: 5,
        title: "Варто кожної гривні!",
        comment:
          "Комплект неймовірний. Компресія відчувається на всіх м'язах. Матеріал преміум.",
        isApproved: true,
        userId: "u4",
        user: { name: "Андрій", email: "test4@test.com" },
        productId: "p8",
        createdAt: new Date("2026-06-01"),
      },
    ],
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-06-01"),
  },
];

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Компресійний одяг для твого тренування",
    subtitle: "Преміальна якість для дорослих та дітей",
    description: "",
    buttonText: "",
    link: "/catalog",
    isActive: true,
    order: 0,
    mode: "image_only",
    useTextContent: false,
    desktopImage: "",
    tabletImage: "",
    mobileImage: "",
    objectFit: "cover",
    positionX: 0,
    positionY: 0,
    objectPosition: "center",
    scale: 1.0,
    width: { desktop: "100%", tablet: "100%", mobile: "100%" },
    height: { desktop: 750, tablet: 650, mobile: 500 },
    maxWidth: { desktop: 1440, tablet: 768, mobile: 375 },
    maxHeight: { desktop: 900, tablet: 800, mobile: 700 },
    aspectRatio: { desktop: "auto", tablet: "auto", mobile: "auto" },
    fullWidth: { desktop: true, tablet: true, mobile: true },
    fullHeight: { desktop: false, tablet: false, mobile: false },
    margin: {
      desktop: { desktop: 0, tablet: 0, mobile: 0 },
      tablet: { desktop: 0, tablet: 0, mobile: 0 },
      mobile: { desktop: 0, tablet: 0, mobile: 0 },
    },
    padding: {
      desktop: { desktop: 0, tablet: 0, mobile: 0 },
      tablet: { desktop: 0, tablet: 0, mobile: 0 },
      mobile: { desktop: 0, tablet: 0, mobile: 0 },
    },
    overlay: {
      enabled: false,
      color: "#000000",
      opacity: 0.5,
      gradientEnabled: false,
      gradientDirection: "to bottom",
    },
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("uk-UA", {
    style: "currency",
    currency: "UAH",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getAverageRating(reviews: Product["reviews"]): number {
  if (reviews.length === 0) return 0;
  const sum = reviews.reduce((acc, r) => acc + r.rating, 0);
  return sum / reviews.length;
}
